config/urls.py
# packages
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('vandelay/', include('project.vandelay.urls')),
    path('', include('project.docent.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/docent/urls.py
from django.urls import path, include
from . import views

app_name = "docent"
urlpatterns = [
    path("", views.home, name="home"),
    path("exhibitions/", views.exhibition_index, name="exhibition_index"),
    path(
        "exhibitions/page/<int:page>", views.exhibition_index, name="exhibition_index"
    ),
    path("exhibitions/<slug:slug>/", views.exhibition_detail, name="exhibition_detail"),
    path("artists/", views.artist_index, name="artist_index"),
    path("artists/<slug:slug>/", views.artist_detail, name="artist_detail"),
    path("news/", views.news_index, name="news_index"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("search-collection/", views.search_collection, name="search_collection"),
    path("collection/<slug:slug>/", views.artwork_detail, name="artwork_detail"),
    # path('myadmin/gridpicker', views.GridPicker.as_view(), name='gridpicker'),
    # path('myadmin/', admin_site.urls),
    # path('artists/<slug:slug>/', views.artist_detail, name='artist_detail'),
    # path('artists/', views.artist_index, name='artist_index'),
    # path('search/', views.search_collection, name='search_collection'),
    # path('work/<slug:slug>/', views.work_detail, name='work_detail'),
    # path('pdf/', views.print_pdf, name='print_pdf'),
    # path('image-autocomplete/', views.ImageAutocomplete.as_view(), name='image_autocomplete'),
]

templates/exhibition/current-1.html
{% load i18n %}

<header class="single-current-exh-header section-header region t-4 d-4 w-4">
    <h1 class="page-title vh">{% trans "Exhibitions" %}</h1>
    <h2 class="section-hed underlined right pg-t-w-1">{% trans "Current Exhibitions" %}</h2>
</header>
<div class="single-curr-exh">
    <img src="{{ exhibition.featured_image.img.crop.1040x1040 }}" alt="" class="region t-8 d-8 w-8">
    <header class="region t-4 d-4 w-4">
        <h3 class="title"><a href="{% url 'docent:exhibition_detail' exhibition.slug %}">{{ exhibition.title }}</a></h3>
        <dl>
            <dt class="vh">{% trans "Artists" %}</dt>
            <dd class="artists">{{ exhibition.display_artists }}</dd>
            <dt class="vh">{% trans "Dates" %}</dt>
            <dd class="dates">{{ exhibition.display_dates }}</dd>
        </dl>
    </header>
</div>

templates/exhibition/current-multi.html
{% load i18n %}

<header class="section-header region t-4 d-4 w-4">
    <h1 class="page-title vh">{% trans "Exhibitions" %}</h1>
    <h2 class="section-hed underlined right pg-t-w-1">{% trans "Current Exhibitions" %}</h2>
</header>
<div class="section-content region t-8 d-8 w-8">
    <ul class="multi-current-exh-list lago-grid m1-one m2-two t-two d-two w-two">
        {% for exhibition in exhibitions %}
        <li>
            {% include 'components/tiles/exhibit.html' with exhibition=exhibition img_size='medium' type='current' show_artists=True additional_classes='tile-exhibit-current' %}
        </li>
        {% endfor %}
    </ul>
</div>

templates/exhibition/detail.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% if exhibition %}{{ exhibition.title }}{% else %}{% trans "Exhibition Detail" %}{% endif %}{% endblock %}

{% block content %}
<main id="main" class="content single-exh">

    {% if exhibition %}
    <section>
        <div class="wrap">
            <div class="single-exh-main region t-4 d-4 w-4">
				<header class="single-exh-header">
                    <h1 class="post-title underlined right">{{ exhibition.title }}</h1>
                    <p class="artist-names h2"><span class="vh">{% trans "Artists" %}: </span>{{ exhibition.display_artists }}</p>
                </header>
                <p class="vh">{% trans "Exhibition Information" %}:</p>
                <dl class="single-exh-dl exhibit-dl">
                    <dt class="vh">{% trans "Dates" %}</dt>
                    <dd class="dates">{{ exhibition.display_dates }}</dd>
                    {% if exhibition.reception %}
                        <dt class="reception inline">{% trans "Opening Reception:" %}</dt>
                        <dd class="reception inline">{{ exhibition.reception }}</dd>
                    {% endif %}
                    {% if exhibition.artist_in_attendance %}
                        <dt class="attendance block">{% trans "Artist in attendance" %}</dt>
                        <dd class="vh">{% trans "Yes" %}</dd>
                    {% endif %}
                </dl>
                <div class="single-exh-entry-content entry-content">
                    {{ exhibition.description|safe }}
                </div>
            </div>

            <div class="single-exh-images region t-8 d-8 w-8">
                <h2 class="vh">{% trans "Exhibition Images" %}</h2>
                {% if exhibition.images.exists %}
                    <ul class="lago-gallery lago-grid m1-two m2-two t-three d-three w-three">
                        {% for image in exhibition.images.all %}
                            <li>
                                {% include 'components/tiles/lightbox-image.html' with image=image catalogue_work=image.artwork_featured_image.first %}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>{% trans "No images found" %}</p>
                {% endif %}
            </div>

        </div>
    </section>
    {% endif %}

</main>
{% endblock %}

{% block footer_js %}
  {{ block.super }}
  {% load static %}
  <script src="{% static 'docent/js/public/src/modaal.js' %}"></script>
  <script src="{% static 'docent/js/public/src/modaal-init.js' %}"></script>
{% endblock %}

templates/exhibition/index.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "Exhibitions" %}{% endblock %}

{% block content %}
<main id="main" class="content pg-exhibitions">

    {% if exhibitions_current %}
    <section class="current exhibits">
        <div class="wrap cf">
            {% if exhibitions_current.count == 1 %}
                {% include 'exhibition/current-1.html' with exhibition=exhibitions_current.0 %}
            {% else %}
                {% include 'exhibition/current-multi.html' with exhibitions=exhibitions_current %}
            {% endif %}
        </div>
    </section>
    {% endif %}

    {% if exhibitions_upcoming %}
    <section class="upcoming exhibits">
        <div class="wrap cf">
            <header class="section-header region t-4 d-4 w-4">
                {% if title_section == 'upcoming' %}
                    <h1 class="page-title vh">{% trans 'Exhibitions' %}</h1>
                    <h2 class="section-hed underlined right pg-t-w-1">{% trans 'Upcoming Exhibitions' %}</h2>
                {% else %}
                    <h2 class="section-hed underlined right">{% trans 'Upcoming Exhibitions' %}</h2>
                {% endif %}
            </header>
            {% if exhibitions_upcoming.count == 1 %}
                {% include 'exhibition/upcoming-1.html' with result=exhibitions_upcoming.0 %}
            {% elif exhibitions_upcoming.count == 2 %}
                {% include 'exhibition/upcoming-2.html' with exhibitions=exhibitions_upcoming classes=upcoming_exhibits_classes %}
            {% else %}
                {% include 'exhibition/upcoming-2-plus.html' with exhibitions=exhibitions_upcoming classes=upcoming_exhibits_classes %}
            {% endif %}
        </div>
    </section>
    {% endif %}
    
    {% if exhibitions_past %}
    <section class="past-exhibits lago-grid-container-indented padded-section">
        <div class="wrap">
            <div class="region">
                <header class="section-header">
                {% if title_section == 'past' %}
                    <h1 class="page-title vh">{% trans "Exhibitions" %}</h1>
                    <h2 class="section-title section-hed underlined right pg-t-w-1">{% trans "Past Exhibitions" %}</h2>
                {% else %}
                    <h2 class="section-title section-hed underlined right">{% trans "Past Exhibitions" %}</h2>
                {% endif %}
                </header>
                <ul class="lago-grid m1-one m2-two t-three d-three w-three">
                    {% for exhibition in exhibitions_past %}
                    <li>
                        {% include 'components/tiles/exhibit.html' with exhibition=exhibition img_size='small' type='past' show_artists=False %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
    {% endif %}

    <nav class="index-pagination search-results-pagination">
        <div class="wrap">
            <div class="step-links region">
                <span class="current">
                    Page {{ exhibitions_past.number }} of {{ exhibitions_past.paginator.num_pages }}
                </span>
                <span class="prev-options">
                    {% if exhibitions_past.has_previous %}
                        <a href="{% url 'docent:exhibition_index' page=1 %}" class="jump">&laquo; <span class="vh">first</span></a>
                        <a href="{% url 'docent:exhibition_index' page=exhibitions_past.previous_page_number %}" class="increment">previous</a>
                    {% endif %}
                </span>
                <span class="next-options">
                    {% if exhibitions_past.has_next %}
                        <a href="{% url 'docent:exhibition_index' page=exhibitions_past.next_page_number %}" class="increment">next</a>
                        <a href="{% url 'docent:exhibition_index' page=exhibitions_past.paginator.num_pages %}" class="jump"><span class="vh">last</span> &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </nav>

</main>
{% endblock %}

templates/exhibition/upcoming-1.html
<div class="section-content region t-8 d-8 w-8">
    {% include 'components/tiles/exhibit.html' with exhibition=result img_size='large' type='upcoming' show_artists=True additional_classes='tile-exhibit-upcoming' %}
</div>

templates/exhibition/upcoming-2-plus.html
<div class="section-content region multi-upc-exh-region">
    <ul class="lago-grid {{ classes }}">
        {% for exhibition in exhibitions %}
        <li>
            {% include 'components/tiles/exhibit.html' with exhibition=exhibition img_size='medium' type='upcoming' show_artists=True additional_classes='tile-exhibit-upcoming' %}
        </li>
        {% endfor %}
    </ul>
</div>

templates/exhibition/upcoming-2.html
<div class="section-content region t-8 d-8 w-8">
    <ul class="lago-grid {{ classes }}">
        {% for exhibition in exhibitions %}
        <li>
            {% include 'components/tiles/exhibit.html' with exhibition=exhibition img_size='medium' type='upcoming' show_artists=True additional_classes='tile-exhibit-upcoming' %}
        </li>
        {% endfor %}
    </ul>
</div>