config/urls.py
# packages
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('vandelay/', include('project.vandelay.urls')),
    path('', include('project.docent.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/docent/urls.py
from django.urls import path, include
from . import views

app_name = "docent"
urlpatterns = [
    path("", views.home, name="home"),
    path("exhibitions/", views.exhibition_index, name="exhibition_index"),
    path(
        "exhibitions/page/<int:page>", views.exhibition_index, name="exhibition_index"
    ),
    path("exhibitions/<slug:slug>/", views.exhibition_detail, name="exhibition_detail"),
    path("artists/", views.artist_index, name="artist_index"),
    path("artists/<slug:slug>/", views.artist_detail, name="artist_detail"),
    path("news/", views.news_index, name="news_index"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("search-collection/", views.search_collection, name="search_collection"),
    path("collection/<slug:slug>/", views.artwork_detail, name="artwork_detail"),
    # path('myadmin/gridpicker', views.GridPicker.as_view(), name='gridpicker'),
    # path('myadmin/', admin_site.urls),
    # path('artists/<slug:slug>/', views.artist_detail, name='artist_detail'),
    # path('artists/', views.artist_index, name='artist_index'),
    # path('search/', views.search_collection, name='search_collection'),
    # path('work/<slug:slug>/', views.work_detail, name='work_detail'),
    # path('pdf/', views.print_pdf, name='print_pdf'),
    # path('image-autocomplete/', views.ImageAutocomplete.as_view(), name='image_autocomplete'),
]

templates/artworks/detail.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% if artwork %}{{ artwork.title }}{% else %}{% trans "Artwork Detail" %}{% endif %}{% endblock %}

{% block content %}
<main id="main" class="single-work {{ main_classes }}">

    <!-- =======================================
    THE MAIN SECTION w/ title, artist, work, 
    details, contact form
	============================================ -->
    <section class="padded-section">
        <div class="wrap">
            
            <div class="single-details region t-4 d-4 w-4">

                <header class="section-header component">
                    <h1 class="post-title underlined right">{{ artwork.title }}</h1>
                    <p class="artist-name h2"><span class="vh">{% trans "Artist" %}: </span><{{ artwork.artist }}</p>
                </header>

                <div class="single-work-inquiry-prompt-space component">
                    <button id="open-single-work-contact-modal" class="open-contact-modal" data-target="single-work-contact-modal">{% trans "Inquire About This Work" %}</button>
                </div>

                <div class="component">
                    {% if details_list %}
                        <ul class="single-work-details">
                            {% if 'mediums' in details_list %}
                            <li><span>{% trans "Medium" %}</span> {{ details_list.mediums }}</li>
                            {% endif %}
                            {% if 'variations' in details_list %}
                                {% for v in details_list.variations %}
                                    <li><span>{% trans "Size" %} {{ forloop.counter }}</span> {{ v }}</li>
                                {% endfor %}
                            {% endif %}
                            {% if 'size' in details_list %}
                                <li><span>{% trans "Size" %}</span> {{ details_list.size }}</li>
                            {% endif %}
                            {% if 'price' in details_list %}
                                <li><span>{% trans "Price" %}</span> {{ details_list.price }}</li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>

            </div>

            {% if artwork.ar_ios or artwork.ar_android %}
			<div class="main-image-space has-ar region t-8 d-8 w-8" data-role="lightbox-create">
                Do AR stuff here first
                {% include 'components/tiles/lightbox-image.html' with image=artwork.featured_image catalogue_work=artwork.featured_image %}
			</div>
			{% else %}
			<div class="main-image-space region t-8 d-8 w-8" data-role="lightbox-create">
                {% include 'components/tiles/lightbox-image.html' with image=artwork.featured_image catalogue_work=artwork.featured_image %}
            </div>
			{% endif %}
        </div>
    </section>

    {% if artwork.artist.description %}
    <section class="artist-about padded-section">
        <div class="wrap">
            <header class="section-header region t-4 d-4 w-4">
                <h2 class="section-hed underlined right">{% trans "About " %}{{ artwork.artist }}</h2>
            </header>
            <div class="section-content region t-8 d-8 w-8">
                {{ artwork.artist.description|safe }}
            </div>
        </div>
    </section>
    {% endif %}

    {% if other_works %}
    <section class="artist-works lago-grid-container-indented padded-section">
        <div class="wrap">
			<div class="region">
				<header class="section-header elem">
					<h2 class="section-hed underlined right">{% trans "Other Work by" %} {{ artwork.artist }}</h2>
                </header>
                <ul class="lago-grid m1-one m2-two t-three d-three w-three">
                    {% for work in other_works %}
                        <li>
                            <div class="tile">
                                <a href="{% url 'docent:artwork_detail' work.id %}">
                                    <img src="{{ work.featured_image.img.crop.350x350 }}" alt="{{ work }}">
                                </a>
                            </div>
                        </li>
					{% endfor %}
				</ul>
            </div>
        </div>
    </section>
    {% endif %}

    {% block footer_js %}
        {{ block.super }}
        {% load static %}
        <script src="{% static 'docent/js/public/src/modaal.js' %}"></script>
        <script src="{% static 'docent/js/public/src/modaal-init.js' %}"></script>
    {% endblock %}

</main>
{% endblock %}

templates/artworks/index.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans "Search Collection" %}{% endblock %}

{% block content %}
<main id="main" class="{{ main_classes }}" aria-hidden="false">
    <div class="wrap">
        <div class="search-filters region t-4 d-3 w-3">
            <header class="page-header">
                <h1 class="post-title underlined">{% trans "Search the Collection" %}</h1>
            </header>
            <form id="ww-search-form" class="responsive-form" method="get" action="">
                
                {% csrf_token %}
                {{ form }}
                
                <div class="component">
                    <p class="component-title">{% trans 'Results' %} <span class="vh">{% trans 'Found' %}:</span></p>
                    <p id="search-filters-num-results"><i>{% if num_results %}{{ num_results }}{% else %}0{% endif %} {% if num_results == 1 %} {% trans 'work' %}{% else %}{% trans 'works' %}{% endif %}</i></p>
                    <p class="vh"><a href="#search-results">{% trans 'Jump to search results' %}</a></p>
                    <p id="clear-search-filters-top-p" {% if not filters_chosen %}style="display:none"{% endif %}><a href="{% url 'docent:search_collection' %}" id="clear-search-filters-top" class="clear-search-filters">{% trans 'Clear filters' %}</a></p>
                </div>

                <!-- PRICE -->
                <div class="range-component component">
                    <div class="component-group hide-if-js">
                        <label for="search-filters-min-price" class="component-title">{% trans 'Min. Price' %}</label>
                        <div class="range-value-indicator"><span>{% if filters.price_min.selected %}{{ filters.price_min.selected.string }}{% else %}{{ filters.price_min.limit.string }}{% endif %}</span></div>
                        <input id="search-filters-min-price" name="price_min" class="range-input" type="range" min="{{ filters.min_price.limit.raw }}" max="{{ filters.max_price.limit.raw }}" value="{% if filters.min_price.selected %}{{ filters.min_price.selected.raw }}{% else %}{{ filters.min_price.limit.raw }}{% endif %}">
                    </div>
                    <div class="component-group hide-if-js">
                        <label for="search-filters-max-price" class="component-title">{% trans 'Max. Price' %}</label>
                        <div class="range-value-indicator"><span>{% if filters.price_max.selected %}{{ filters.price_max.selected.string }}{% else %}{{ filters.price_max.limit.string }}{% endif %}</span></div>
                        <input id="search-filters-max-price" name="price_max" class="range-input" type="range" min="{{ filters.price_min.limit.raw }}" max="{{ filters.price_max.limit.raw }}" value="{% if filters.price_max.selected %}{{ filters.price_max.selected.raw }}{% else %}{{ filters.price_max.limit.raw }}{% endif %}">
                    </div>
                    <div class="component-group">
                        <label for="search-filter-min-max-price" class="component-title">{% trans 'Price Range' %}</label>
                        <p id="price-multirange-helper" class="vh">{% trans 'Use tab to access range slider, and up and down arrow keys to change values' %}</p>
                        <input id="search-filter-min-max-price" name="" type="text" describedby="price-multirange-helper" class="multirange-dummy" data-units="dollars" readonly tabindex="-1">
                        <div class="multirange-input" data-step="50" data-min-target="search-filters-min-price" data-max-target="search-filters-max-price" data-min="{{ filters.price_min.limit.raw }}" data-max="{{ filters.price_max.limit.raw }}" data-min-value="{% if filters.price_min.selected %}{{ filters.price_min.selected.raw }}{% else %}{{ filters.price_min.limit.raw }}{% endif %}" data-max-value="{% if filters.price_max.selected %}{{ filters.price_max.selected.raw }}{% else %}{{ filters.price_max.limit.raw }}{% endif %}" data-units="dollars" tabindex="0"></div>
                    </div>
                </div>

                <!-- HEIGHT AND WIDTH -->
                <div class="range-component component">
                    <div class="component-group hide-if-js">
                        <label for="search-filters-min-height" class="component-title">{% trans 'Min. Height' %}</label>
                        <div class="range-value-indicator"><span>{% if filters.height_min.selected %}{{ filters.height_min.selected.string }}{% else %}{{ filters.height_min.limit.string}}{% endif %}</span></div>
                        <input id="search-filters-min-height" name="height_min" class="range-input" type="range" min="{{ filters.height_min.limit.raw }}" max="{{ filters.height_max.limit.raw }}" value="{% if filters.height_min.selected %}{{ filters.height_min.selected.raw }}{% else %}{{ filters.height_min.limit.raw }}{% endif %}">
                    </div>
                    <div class="component-group hide-if-js">
                        <label for="search-filters-max-height" class="component-title">{% trans 'Max. Height' %}</label>
                        <div class="range-value-indicator"><span>{% if filters.height_max.selected %}{{ filters.height_max.selected.string }}{% else %}{{ filters.height_max.limit.string }}{% endif %}</span></div>
                        <input id="search-filters-max-height" name="height_max" class="range-input" type="range" min="{{ filters.height_min.limit.raw }}" max="{{ filters.height_max.limit.raw }}" value="{% if filters.height_max.selected %}{{ filters.height_max.selected.raw }}{% else %}{{ filters.height_max.limit.raw }}{% endif %}">
                    </div>
                    <div class="component-group">
                        <label for="search-filter-min-max-height" class="component-title">{% trans 'Height Range' %}</label>
                        <p id="height-multirange-helper" class="vh">{% trans 'Use tab to access range slider, and up and down arrow keys to change values' %}</p>
                        <input id="search-filter-min-max-height" name="" type="text" class="multirange-dummy" data-units="inches" describedyb="height-multirange-helper" readonly tabindex="-1">
                        <div class="multirange-input" data-step="1" data-min-target="search-filters-min-height" data-max-target="search-filters-max-height" data-min="{{ filters.height_min.limit.raw }}" data-max="{{ filters.height_max.limit.raw }}" data-min-value="{% if filters.height_min.selected %}{{ filters.height_min.selected.raw }}{% else %}{{ filters.height_min.limit.raw }}{% endif %}" data-max-value="{% if filters.height_max.selected %}{{ filters.height_max.selected.raw }}{% else %}{{ filters.height_max.limit.raw }}{% endif %}" data-units="inches"></div>
                    </div>
                    <div class="component-group hide-if-js">
                        <label for="search-filters-min-width" class="component-title">{% trans 'Min. Width' %}</label>
                        <div class="range-value-indicator"><span>{% if filters.width_min.selected %}{{ filters.width_min.selected.string }}{% else %}{{ filters.width_min.limit.string }}{% endif %}</span></div>
                        <input id="search-filters-min-width" name="width_min" class="range-input" type="range" min="{{ filters.width_min.limit.raw }}" max="{{ filters.width_max.limit.raw }}" value="{% if filters.width_min.selected %}{{ filters.width_min.selected.raw }}{% else %}{{ filters.width_min.limit.raw }}{% endif %}">
                    </div>
                    <div class="component-group hide-if-js">
                        <label for="search-filters-max-width" class="component-title">{% trans 'Max. Width' %}</label>
                        <div class="range-value-indicator"><span>{% if filters.width_max.selected %}{{ filters.width_max.selected.string }}{% else %}{{ filters.width_max.limit.string }}{% endif %}</span></div>
                        <input id="search-filters-max-width" name="width_max" class="range-input" type="range" min="{{ filters.width_min.limit.raw }}" max="{{ filters.width_max.limit.raw }}" value="{% if filters.width_max.selected %}{{ filters.width_max.selected.raw }}{% else %}{{ filters.width_max.limit.raw }}{% endif %}">
                    </div>
                    <div class="component-group">
                        <label for="search-filter-min-max-width" class="component-title">{% trans 'Width Range' %}</label>
                        <p id="width-multirange-helper" class="vh">{% trans 'Use tab to access range slider, and up and down arrow keys to change values' %}</p>
                        <input id="search-filter-min-max-width" name="" type="text" class="multirange-dummy" describedby="width-multirange-helper" readonly aria-hidden="true" tabindex="-1">
                        <div class="multirange-input" data-step="1" data-min-target="search-filters-min-width" data-max-target="search-filters-max-width" data-min="{{ filters.width_min.limit.raw }}" data-max="{{ filters.width_max.limit.raw }}" data-min-value="{% if filters.width_min.selected %}{{ filters.width_min.selected.raw }}{% else %}{{ filters.width_min.limit.raw }}{% endif %}" data-max-value="{% if filters.width_max.selected %}{{ filters.width_max.selected.raw }}{% else %}{{ filters.width_max.limit.raw }}{% endif %}" data-units="inches"></div>
                    </div>
                </div>
                
                <!-- SUBMIT -->
                <div class="search-component component">
                    <input type="hidden" name="action" value="search_collection">
                    <input type="hidden" name="submitted" value="true">
                    <p><input type="submit" value="{% trans 'Apply filters' %}" id="ww-search-form-submit"></p>
                    <a href="{% url 'docent:search_collection' %}" id="clear-search-filters-bottom" class="clear-search-filters">{% trans "Clear filters" %}</a>
                </div>
            </form>
        </div>
        <!-- THE MAIN SEARCH RESULT AREA -->
        <div id="search-results" class="search-results region t-8 d-9 w-9" data-current-page="1" data-total-pages="1" data-total-results="1">    
            <h2 class="vh">{% trans "Search Results" %}</h2>
            {% if results %}
            <ul id="search-results-list" class="lago-grid m1-one m2-two t-three d-three w-three" tabindex="-1">
                {% for result in results %}
                <li>
                    <div class="tile-expanded tile">
                        <a href="{% url 'docent:artwork_detail' result.slug %}">{{ result.title }}</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
    </div>
    
    {% if artists_active %}
    <section class="active-artists lago-grid-container-indented padded-section">
        <div class="wrap">
            <div class="region">
                <header class="section-header">
                    <h1 class="page-title section-hed underlined right pg-t-w-1">{% trans "Artists"%}</h1>
                    <h2 class="section-title vh">{% trans 'Main Artists' %}</h2>
                </header>
                <ul class="lago-grid m1-one m2-two t-three d-three w-three">
                    {% for a in artists_active %}
                    <li>
                        <article class="tile tile-artist">
                            <h3><a href="{% url 'docent:artist_detail' a.slug %}">{{ a.title }}</a></h3>
                        </article>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
    {% endif %}

</main>
{% endblock %}

{% block footer_js %}
    {{ block.super }}
    <script src="{% static 'docent/js/public/dist/core.min.js' %}"></script>
    <script src="{% static 'docent/js/public/dist/widget.min.js' %}"></script>
    <script src="{% static 'docent/js/public/dist/mouse.min.js' %}"></script>
    <script src="{% static 'docent/js/public/dist/slider.min.js' %}"></script>
    <script src="{% static 'docent/js/public/src/ww-scour-range-controls.js' %}"></script>
{% endblock %}