config/urls.py
# packages
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('vandelay/', include('project.vandelay.urls')),
    path('', include('project.docent.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/docent/urls.py
from django.urls import path, include
from . import views

app_name = "docent"
urlpatterns = [
    path("", views.home, name="home"),
    path("exhibitions/", views.exhibition_index, name="exhibition_index"),
    path(
        "exhibitions/page/<int:page>", views.exhibition_index, name="exhibition_index"
    ),
    path("exhibitions/<slug:slug>/", views.exhibition_detail, name="exhibition_detail"),
    path("artists/", views.artist_index, name="artist_index"),
    path("artists/<slug:slug>/", views.artist_detail, name="artist_detail"),
    path("news/", views.news_index, name="news_index"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("search-collection/", views.search_collection, name="search_collection"),
    path("collection/<slug:slug>/", views.artwork_detail, name="artwork_detail"),
    # path('myadmin/gridpicker', views.GridPicker.as_view(), name='gridpicker'),
    # path('myadmin/', admin_site.urls),
    # path('artists/<slug:slug>/', views.artist_detail, name='artist_detail'),
    # path('artists/', views.artist_index, name='artist_index'),
    # path('search/', views.search_collection, name='search_collection'),
    # path('work/<slug:slug>/', views.work_detail, name='work_detail'),
    # path('pdf/', views.print_pdf, name='print_pdf'),
    # path('image-autocomplete/', views.ImageAutocomplete.as_view(), name='image_autocomplete'),
]

templates/news/detail.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Home{% endblock %}

{% block content %}
<main id="main" class="{{ main_classes }}">

    {% if post %}
    <!-- =======================================
	THE MAIN SECTION
	============================================ -->
	<section id="section-main" class="section-main" tabindex="-1">
        <div class="wrap cf">
    
            <div class="single-artist-main region t-4 d-4 w-4">                
                <header class="single-artist-header">
                    <h1 class="post-title underlined right">{{ post.title }}</h1>
                    <p>{{ post.created_at }}</p>
                </header>
            </div>  
            
            <div class="single-artist-images region t-8 d-8 w-8">
                {{ post.description|safe }}
            </div>
                        
        </div>
    </section>
    {% endif %}

</main>
{% endblock %}

templates/news/index.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Home{% endblock %}

{% block content %}
<main id="main" class="{{ main_classes }}" aria-hidden="false">
    
    {% if posts %}
    <section class="active-artists lago-grid-container-indented padded-section">
        <div class="wrap">
            <div class="region">
                <header class="section-header">
                    <h1 class="page-title section-hed underlined right pg-t-w-1">{% trans "News"%}</h1>
                </header>
                <ul class="lago-grid m1-one m2-two t-three d-three w-three">
                    {% for p in posts %}
                    <li>
                        <article class="tile tile-artist">
                            <h3><a href="{% url 'docent:news_detail' p.slug %}">{{ p.title }}</a></h3>
                        </article>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>
    {% endif %}

</main>
{% endblock %}