config/urls.py
# packages
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/',admin.site.urls),
    path('account/', include('django.contrib.auth.urls')),
    path('vandelay/', include('project.vandelay.urls')),
    path('', include('project.docent.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/docent/urls.py
from django.urls import path, include
from . import views

app_name = "docent"
urlpatterns = [
    path("", views.home, name="home"),
    path("exhibitions/", views.exhibition_index, name="exhibition_index"),
    path(
        "exhibitions/page/<int:page>", views.exhibition_index, name="exhibition_index"
    ),
    path("exhibitions/<slug:slug>/", views.exhibition_detail, name="exhibition_detail"),
    path("artists/", views.artist_index, name="artist_index"),
    path("artists/<slug:slug>/", views.artist_detail, name="artist_detail"),
    path("news/", views.news_index, name="news_index"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("search-collection/", views.search_collection, name="search_collection"),
    path("collection/<slug:slug>/", views.artwork_detail, name="artwork_detail"),
    # path('myadmin/gridpicker', views.GridPicker.as_view(), name='gridpicker'),
    # path('myadmin/', admin_site.urls),
    # path('artists/<slug:slug>/', views.artist_detail, name='artist_detail'),
    # path('artists/', views.artist_index, name='artist_index'),
    # path('search/', views.search_collection, name='search_collection'),
    # path('work/<slug:slug>/', views.work_detail, name='work_detail'),
    # path('pdf/', views.print_pdf, name='print_pdf'),
    # path('image-autocomplete/', views.ImageAutocomplete.as_view(), name='image_autocomplete'),
]

templates/base.html
{% load static i18n %}

<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'docent/css/style.css' %}">
  
  <style>
    @font-face {font-family: 'TradeGothicLT';src: url('{% static "docent/type/27C68E_0_0.eot" %}');src: url('{% static "docent/type/27C68E_0_0.eot" %}?#iefix') format('embedded-opentype'),url('{% static "docent/type/27C68E_0_0.woff" %}') format('woff'),url('{% static "docent/type/27C68E_0_0.ttf" %}') format('truetype');}
    @font-face {font-family: 'TradeGothicLT-CondEighteen';src: url('{% static "docent/type/27C68E_1_0.eot" %}');src: url('{% static "docent/type/27C68E_1_0.eot?#iefix" %}') format('embedded-opentype'),url('{% static "docent/type/27C68E_1_0.woff" %}27C68E_1_0.woff') format('woff'),url('{% static "docent/type/27C68E_1_0.ttf" %}') format('truetype');}
    @font-face {font-family: 'TradeGothicLTCom-Bd2';src: url('{% static "docent/type/27C68E_2_0.eot" %}');src: url('{% static "docent/type/27C68E_2_0.eot?#iefix" %}') format('embedded-opentype'),url('{% static "docent/type/27C68E_2_0.woff" %}') format('woff'),url('{% static "docent/type/27C68E_2_0.ttf" %}') format('truetype');}
    @font-face {font-family: 'TradeGothicLTCom-Cn18Obl';src: url('{% static "docent/type/27C68E_3_0.eot" %}');src: url('{% static "docent/type/27C68E_3_0.eot?#iefix" %}') format('embedded-opentype'),url('{% static "docent/type/27C68E_3_0.woff" %}') format('woff'),url('{% static "docent/type/27C68E_3_0.ttf" %}') format('truetype');}
    @font-face {font-family: 'TradeGothicLTCom-BdCn20';src: url('{% static "docent/type/27C68E_4_0.eot" %}');src: url('{% static "docent/type/27C68E_4_0.eot?#iefix" %}') format('embedded-opentype'),url('{% static "docent/type/27C68E_4_0.woff" %}') format('woff'),url('{% static "docent/type/27C68E_4_0.ttf" %}') format('truetype');}
  </style>

  <link rel="apple-touch-icon" href="{% static 'docent/favicons/apple-touch-icon.png' %}">
	<link rel="icon" href="{% static 'docent/favicons/favicon.png' %}">
	<!--[if IE]>
		<link rel="shortcut icon" href="{% static 'docent/favicons/favicon.ico' %}">
	<![endif]-->
	<meta name="msapplication-TileColor" content="#f01d4f">
	<meta name="msapplication-TileImage" content="{% static 'docent/favicons/win8-tile-icon.png' %}">
  	<meta name="theme-color" content="#121212">


</head>
<body class="{% if body_classes %}{{body_classes}}{% endif %}">

  <a href="#main" class="skip-link"><{% trans "Skip to main content" %}</a>
	<div id="container">
    
    <header class="site-header" itemscope itemtype="http://schema.org/WPHeader">
			<div id="inner-header" class="wrap cf">
				<nav class="main-nav" itemscope itemtype="http://schema.org/SiteNavigationElement" aria-label="site">
					<ul id="main-menu" class="main-menu">
            <li class="home"><a href="/"><img src="https://newyork.winstonwachter.com/wp-content/themes/lago/library/images/logo.png" alt="Winston Wachter Fine Art home"></a></li>
            <li><a href="{% url 'docent:exhibition_index' %}">Exhibitions</a></li>
            <li><a href="{% url 'docent:artist_index' %}">Artists</a></li>
            <li><a href="/gallery">Gallery</a></li>
            <li><a href="{% url 'docent:news_index' %}">Studio Visits</a></li>
            <li><a href="{% url 'docent:search_collection' %}">Search</a></li>
          </ul>
				</nav>
			</div>
		</header>
  
    {% block content %}
    {% endblock %}

    {% block footer %}
    <footer id="footer" class="footer" itemscope itemtype="http://schema.org/Footer">
      <div id="inner=footer" class="footer-main wrap">
          {% if request.path == "/" %}
            <div class="global footer-block region t-3 d-3 w-3">
							<dl>
								<dt class="vh">{% trans "Seattle Gallery Address" %}</dt>
								<dd>
									<address>
										<a href="https://goo.gl/maps/tYsqSboamRK2" target="_blank" rel="noopener">203 Dexter Ave <br/>Seattle, WA 98109</a>
									</address>
								</dd>
							</dl>
            </div>
            <div class="global footer-block region t-3 d-3 w-3">
              <dl>
                <dt class="vh">{% trans "Seattle Gallery Contact Information" %}</dt>
                <dd>
                  <address>
                    <a href="mailto:gallery@winstonwachter.com">gallery@&#8203;winstonwachter.com</a><br/>
                    <a href="tel:206-652-5855">206 652 5855</a>
                  </address>
                </dd>
              </dl>
            </div>
            <div class="ny-address global footer-block region t-3 d-3 w-3">
              <dl>
                <dt class="vh">{% trans "New York Gallery Address" %}</dt>
                <dd>
                  <address>
                    <a href="https://goo.gl/maps/fb6H2qkwbDQ2" target="_blank" rel="noopener">530 W 25th St <br/>New York, NY 10001</a>
                  </address>
                </dd>
              </dl>
            </div>
            <div class="ny-contact global footer-block region t-3 d-3 w-3">
              <dl>
                <dt class="vh">{% trans "New York Gallery Contact Information" %}</dt>
                <dd>
                  <address>
                    <a href="mailto:nygallery@winstonwachter.com">nygallery@&#8203;winstonwachter.com</a><br/>
                    <a href="tel:212-255-2718">212 255 2718</a>
                  </address>
                </dd>
              </dl>
            </div>
          {% else %}
            
            <div class="footer-block subscribe region t-6 d-3 w-3">
							<button class="open-contact-modal" data-target="global-contact-modal">{% trans "Subscribe" %} <span class="vh">{% trans "to our Newsletter" %}</span></button>
            </div>
            <div class="footer-block visit region t-6 d-3 w-3">
              <p class="footer-title">{% trans "Visit" %}</p>
              <dl>
                <dt class="vh">{% trans "Gallery Address" %}</dt>
                <dd>
                  <address>
                    <a href="https://goo.gl/maps/pEYFMXJPq3C2" target="_blank" rel="noopener">203 Dexter Ave. N<br/>Seattle, WA 98109</a>
                  </address>
                </dd>
                <dt class="vh">{% trans "Business Hours" %}</dt>
                <dd>Monday - Saturday By Appointment</dd>
              </dl>
            </div>
            <div class="footer-block region t-6 d-3 w-3">
              <p class="footer-title">{% trans "Contact" %} <span class="vh">{% trans "Information" %}</span></p>
              <dl>
                <dt class="vh">{% trans "Email address" %}</dt>
                <dd><a href="mailto:gallery@winstonwachter.com">gallery@winstonwachter.com</a></dd>
                <dt class="vh">{% trans "Phone number" %}</dt>
                <dd><a href="tel:206-652-5855">206-652-5855</a>
              </dl>
            </div>
            <div class="footer-block region t-6 d-3 w-3">
              <p class="footer-title">{% trans "Connect" %}<span class='vh'> {% trans "with us on social media" %}</span></p>
              <ul class="footer-social-menu">
                <li>
                  <a href="https://www.facebook.com/Winston.Wachter" target="_blank" rel="noopener" class="facebook">
                    <span class="vh">{% trans "Our Facebook page" %}</span>
                    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M22.676 0H1.324C.593 0 0 .593 0 1.324v21.352C0 23.408.593 24 1.324 24h11.494v-9.294H9.689v-3.621h3.129V8.41c0-3.099 1.894-4.785 4.659-4.785 1.325 0 2.464.097 2.796.141v3.24h-1.921c-1.5 0-1.792.721-1.792 1.771v2.311h3.584l-.465 3.63H16.56V24h6.115c.733 0 1.325-.592 1.325-1.324V1.324C24 .593 23.408 0 22.676 0"/></svg>
                  </a>
                </li>
                <li>
                  <a href="https://twitter.com/WinstonWachter" target="_blank" rel="noopener" class="twitter">
                    <span class="vh">{% trans "Follow us on Twitter" %}</span>
                    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M23.954 4.569c-.885.389-1.83.654-2.825.775 1.014-.611 1.794-1.574 2.163-2.723-.951.555-2.005.959-3.127 1.184-.896-.959-2.173-1.559-3.591-1.559-2.717 0-4.92 2.203-4.92 4.917 0 .39.045.765.127 1.124C7.691 8.094 4.066 6.13 1.64 3.161c-.427.722-.666 1.561-.666 2.475 0 1.71.87 3.213 2.188 4.096-.807-.026-1.566-.248-2.228-.616v.061c0 2.385 1.693 4.374 3.946 4.827-.413.111-.849.171-1.296.171-.314 0-.615-.03-.916-.086.631 1.953 2.445 3.377 4.604 3.417-1.68 1.319-3.809 2.105-6.102 2.105-.39 0-.779-.023-1.17-.067 2.189 1.394 4.768 2.209 7.557 2.209 9.054 0 13.999-7.496 13.999-13.986 0-.209 0-.42-.015-.63.961-.689 1.8-1.56 2.46-2.548l-.047-.02z"/></svg>
                  </a>
                </li>
                <li>
                  <a href="https://www.instagram.com/winstonwachter" target="_blank" rel="noopener" class="instagram">
                    <span class="vh">{% trans "Follow us on Instagram" %}</span>
                    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z"/></svg>
                  </a>
                </li>
                <li>
                  <a href="mailto:gallery@winstonwachter.com" target="_blank" rel="noopener" class="email">
                    <span class="vh">{% trans "Email us: " %} gallery@winstonwachter.com</span>
                    <svg viewBox="0 0 512 512"><path d="M101.3 141.6v228.9h0.3 308.4 0.8V141.6H101.3zM375.7 167.8l-119.7 91.5 -119.6-91.5H375.7zM127.6 194.1l64.1 49.1 -64.1 64.1V194.1zM127.8 344.2l84.9-84.9 43.2 33.1 43-32.9 84.7 84.7L127.8 344.2 127.8 344.2zM384.4 307.8l-64.4-64.4 64.4-49.3V307.8z"></path></svg>
                  </a>
                </li>
              </ul>
            </div>
          {% endif %}
      </div>
    </footer>
    {% endblock %}

    {% block footer_js %}
      <script src="{% static 'docent/js/public/dist/jquery.js' %}"></script>
    {% endblock %}

  </div>
</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
Home!
{% endblock %}